# Generated by Django 3.2.16 on 2022-12-28 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
                ('is_in_stock', models.BooleanField(default=False)),
                ('size', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
